export const HOMEPAGE_SLUG = '?slug=/'
export const NAV_ENDPOINT = '/api/v1/content/nav'
export const SEARCH_MINIMAL_ENDPOINT = '/api/v1/catalog/search/advanced/minimal'
export const PRODUCT_API_ENDPOINT = '/api/v1/catalog/product/'
export const NEXT_API_NOTIFY_ME_ENDPOINT = '/api/notify-me/'
