export default [
  { code: null, title: 'Country', value: 'Country' },
  { code: 'AF', title: 'Afghanistan', value: 'Afghanistan' },
  { code: 'AX', title: 'Åland Islands', value: 'Åland Islands' },
  { code: 'AL', title: 'Albania', value: 'Albania' },
  { code: 'DZ', title: 'Algeria', value: 'Algeria' },
  { code: 'AS', title: 'American Samoa', value: 'American Samoa' },
  { code: 'AD', title: 'AndorrA', value: 'AndorrA' },
  { code: 'AO', title: 'Angola', value: 'Angola' },
  { code: 'AI', title: 'Anguilla', value: 'Anguilla' },
  { code: 'AQ', title: 'Antarctica', value: 'Antarctica' },
  { code: 'AG', title: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { code: 'AR', title: 'Argentina', value: 'Argentina' },
  { code: 'AM', title: 'Armenia', value: 'Armenia' },
  { code: 'AW', title: 'Aruba', value: 'Aruba' },
  { code: 'AU', title: 'Australia', value: 'Australia' },
  { code: 'AT', title: 'Austria', value: 'Austria' },
  { code: 'AZ', title: 'Azerbaijan', value: 'Azerbaijan' },
  { code: 'BS', title: 'Bahamas', value: 'Bahamas' },
  { code: 'BH', title: 'Bahrain', value: 'Bahrain' },
  { code: 'BD', title: 'Bangladesh', value: 'Bangladesh' },
  { code: 'BB', title: 'Barbados', value: 'Barbados' },
  { code: 'BY', title: 'Belarus', value: 'Belarus' },
  { code: 'BE', title: 'Belgium', value: 'Belgium' },
  { code: 'BZ', title: 'Belize', value: 'Belize' },
  { code: 'BJ', title: 'Benin', value: 'Benin' },
  { code: 'BM', title: 'Bermuda', value: 'Bermuda' },
  { code: 'BT', title: 'Bhutan', value: 'Bhutan' },
  { code: 'BO', title: 'Bolivia', value: 'Bolivia' },
  {
    code: 'BA',
    title: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
  },
  { code: 'BW', title: 'Botswana', value: 'Botswana' },
  { code: 'BV', title: 'Bouvet Island', value: 'Bouvet Island' },
  { code: 'BR', title: 'Brazil', value: 'Brazil' },
  {
    code: 'IO',
    title: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  { code: 'BN', title: 'Brunei Darussalam', value: 'Brunei Darussalam' },
  { code: 'BG', title: 'Bulgaria', value: 'Bulgaria' },
  { code: 'BF', title: 'Burkina Faso', value: 'Burkina Faso' },
  { code: 'BI', title: 'Burundi', value: 'Burundi' },
  { code: 'KH', title: 'Cambodia', value: 'Cambodia' },
  { code: 'CM', title: 'Cameroon', value: 'Cameroon' },
  { code: 'CA', title: 'Canada', value: 'Canada' },
  { code: 'CV', title: 'Cape Verde', value: 'Cape Verde' },
  { code: 'KY', title: 'Cayman Islands', value: 'Cayman Islands' },
  {
    code: 'CF',
    title: 'Central African Republic',
    value: 'Central African Republic',
  },
  { code: 'TD', title: 'Chad', value: 'Chad' },
  { code: 'CL', title: 'Chile', value: 'Chile' },
  { code: 'CN', title: 'China', value: 'China' },
  { code: 'CX', title: 'Christmas Island', value: 'Christmas Island' },
  {
    code: 'CC',
    title: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
  },
  { code: 'CO', title: 'Colombia', value: 'Colombia' },
  { code: 'KM', title: 'Comoros', value: 'Comoros' },
  { code: 'CG', title: 'Congo', value: 'Congo' },
  {
    code: 'CD',
    title: 'Congo, The Democratic Republic of the',
    value: 'Congo, The Democratic Republic of the',
  },
  { code: 'CK', title: 'Cook Islands', value: 'Cook Islands' },
  { code: 'CR', title: 'Costa Rica', value: 'Costa Rica' },
  { code: 'CI', title: "Cote D'Ivoire", value: "Cote D'Ivoire" },
  { code: 'HR', title: 'Croatia', value: 'Croatia' },
  { code: 'CU', title: 'Cuba', value: 'Cuba' },
  { code: 'CY', title: 'Cyprus', value: 'Cyprus' },
  { code: 'CZ', title: 'Czech Republic', value: 'Czech Republic' },
  { code: 'DK', title: 'Denmark', value: 'Denmark' },
  { code: 'DJ', title: 'Djibouti', value: 'Djibouti' },
  { code: 'DM', title: 'Dominica', value: 'Dominica' },
  { code: 'DO', title: 'Dominican Republic', value: 'Dominican Republic' },
  { code: 'EC', title: 'Ecuador', value: 'Ecuador' },
  { code: 'EG', title: 'Egypt', value: 'Egypt' },
  { code: 'SV', title: 'El Salvador', value: 'El Salvador' },
  { code: 'GQ', title: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { code: 'ER', title: 'Eritrea', value: 'Eritrea' },
  { code: 'EE', title: 'Estonia', value: 'Estonia' },
  { code: 'ET', title: 'Ethiopia', value: 'Ethiopia' },
  {
    code: 'FK',
    title: 'Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
  },
  { code: 'FO', title: 'Faroe Islands', value: 'Faroe Islands' },
  { code: 'FJ', title: 'Fiji', value: 'Fiji' },
  { code: 'FI', title: 'Finland', value: 'Finland' },
  { code: 'FR', title: 'France', value: 'France' },
  { code: 'GF', title: 'French Guiana', value: 'French Guiana' },
  { code: 'PF', title: 'French Polynesia', value: 'French Polynesia' },
  {
    code: 'TF',
    title: 'French Southern Territories',
    value: 'French Southern Territories',
  },
  { code: 'GA', title: 'Gabon', value: 'Gabon' },
  { code: 'GM', title: 'Gambia', value: 'Gambia' },
  { code: 'GE', title: 'Georgia', value: 'Georgia' },
  { code: 'DE', title: 'Germany', value: 'Germany' },
  { code: 'GH', title: 'Ghana', value: 'Ghana' },
  { code: 'GI', title: 'Gibraltar', value: 'Gibraltar' },
  { code: 'GR', title: 'Greece', value: 'Greece' },
  { code: 'GL', title: 'Greenland', value: 'Greenland' },
  { code: 'GD', title: 'Grenada', value: 'Grenada' },
  { code: 'GP', title: 'Guadeloupe', value: 'Guadeloupe' },
  { code: 'GU', title: 'Guam', value: 'Guam' },
  { code: 'GT', title: 'Guatemala', value: 'Guatemala' },
  { code: 'GG', title: 'Guernsey', value: 'Guernsey' },
  { code: 'GN', title: 'Guinea', value: 'Guinea' },
  { code: 'GW', title: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { code: 'GY', title: 'Guyana', value: 'Guyana' },
  { code: 'HT', title: 'Haiti', value: 'Haiti' },
  {
    code: 'HM',
    title: 'Heard Island and Mcdonald Islands',
    value: 'Heard Island and Mcdonald Islands',
  },
  {
    code: 'VA',
    title: 'Holy See (Vatican City State)',
    value: 'Holy See (Vatican City State)',
  },
  { code: 'HN', title: 'Honduras', value: 'Honduras' },
  { code: 'HK', title: 'Hong Kong', value: 'Hong Kong' },
  { code: 'HU', title: 'Hungary', value: 'Hungary' },
  { code: 'IS', title: 'Iceland', value: 'Iceland' },
  { code: 'IN', title: 'India', value: 'India' },
  { code: 'ID', title: 'Indonesia', value: 'Indonesia' },
  {
    code: 'IR',
    title: 'Iran, Islamic Republic Of',
    value: 'Iran, Islamic Republic Of',
  },
  { code: 'IQ', title: 'Iraq', value: 'Iraq' },
  { code: 'IE', title: 'Ireland', value: 'Ireland' },
  { code: 'IM', title: 'Isle of Man', value: 'Isle of Man' },
  { code: 'IL', title: 'Israel', value: 'Israel' },
  { code: 'IT', title: 'Italy', value: 'Italy' },
  { code: 'JM', title: 'Jamaica', value: 'Jamaica' },
  { code: 'JP', title: 'Japan', value: 'Japan' },
  { code: 'JE', title: 'Jersey', value: 'Jersey' },
  { code: 'JO', title: 'Jordan', value: 'Jordan' },
  { code: 'KZ', title: 'Kazakhstan', value: 'Kazakhstan' },
  { code: 'KE', title: 'Kenya', value: 'Kenya' },
  { code: 'KI', title: 'Kiribati', value: 'Kiribati' },
  {
    code: 'KP',
    title: "Korea, Democratic People'S Republic of",
    value: "Korea, Democratic People'S Republic of",
  },
  { code: 'KR', title: 'Korea, Republic of', value: 'Korea, Republic of' },
  { code: 'KW', title: 'Kuwait', value: 'Kuwait' },
  { code: 'KG', title: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  {
    code: 'LA',
    title: "Lao People'S Democratic Republic",
    value: "Lao People'S Democratic Republic",
  },
  { code: 'LV', title: 'Latvia', value: 'Latvia' },
  { code: 'LB', title: 'Lebanon', value: 'Lebanon' },
  { code: 'LS', title: 'Lesotho', value: 'Lesotho' },
  { code: 'LR', title: 'Liberia', value: 'Liberia' },
  {
    code: 'LY',
    title: 'Libyan Arab Jamahiriya',
    value: 'Libyan Arab Jamahiriya',
  },
  { code: 'LI', title: 'Liechtenstein', value: 'Liechtenstein' },
  { code: 'LT', title: 'Lithuania', value: 'Lithuania' },
  { code: 'LU', title: 'Luxembourg', value: 'Luxembourg' },
  { code: 'MO', title: 'Macao', value: 'Macao' },
  {
    code: 'MK',
    title: 'Macedonia, The Former Yugoslav Republic of',
    value: 'Macedonia, The Former Yugoslav Republic of',
  },
  { code: 'MG', title: 'Madagascar', value: 'Madagascar' },
  { code: 'MW', title: 'Malawi', value: 'Malawi' },
  { code: 'MY', title: 'Malaysia', value: 'Malaysia' },
  { code: 'MV', title: 'Maldives', value: 'Maldives' },
  { code: 'ML', title: 'Mali', value: 'Mali' },
  { code: 'MT', title: 'Malta', value: 'Malta' },
  { code: 'MH', title: 'Marshall Islands', value: 'Marshall Islands' },
  { code: 'MQ', title: 'Martinique', value: 'Martinique' },
  { code: 'MR', title: 'Mauritania', value: 'Mauritania' },
  { code: 'MU', title: 'Mauritius', value: 'Mauritius' },
  { code: 'YT', title: 'Mayotte', value: 'Mayotte' },
  { code: 'MX', title: 'Mexico', value: 'Mexico' },
  {
    code: 'FM',
    title: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
  },
  { code: 'MD', title: 'Moldova, Republic of', value: 'Moldova, Republic of' },
  { code: 'MC', title: 'Monaco', value: 'Monaco' },
  { code: 'MN', title: 'Mongolia', value: 'Mongolia' },
  { code: 'MS', title: 'Montserrat', value: 'Montserrat' },
  { code: 'MA', title: 'Morocco', value: 'Morocco' },
  { code: 'MZ', title: 'Mozambique', value: 'Mozambique' },
  { code: 'MM', title: 'Myanmar', value: 'Myanmar' },
  { code: 'NA', title: 'Namibia', value: 'Namibia' },
  { code: 'NR', title: 'Nauru', value: 'Nauru' },
  { code: 'NP', title: 'Nepal', value: 'Nepal' },
  { code: 'NL', title: 'Netherlands', value: 'Netherlands' },
  { code: 'AN', title: 'Netherlands Antilles', value: 'Netherlands Antilles' },
  { code: 'NC', title: 'New Caledonia', value: 'New Caledonia' },
  { code: 'NZ', title: 'New Zealand', value: 'New Zealand' },
  { code: 'NI', title: 'Nicaragua', value: 'Nicaragua' },
  { code: 'NE', title: 'Niger', value: 'Niger' },
  { code: 'NG', title: 'Nigeria', value: 'Nigeria' },
  { code: 'NU', title: 'Niue', value: 'Niue' },
  { code: 'NF', title: 'Norfolk Island', value: 'Norfolk Island' },
  {
    code: 'MP',
    title: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
  },
  { code: 'NO', title: 'Norway', value: 'Norway' },
  { code: 'OM', title: 'Oman', value: 'Oman' },
  { code: 'PK', title: 'Pakistan', value: 'Pakistan' },
  { code: 'PW', title: 'Palau', value: 'Palau' },
  {
    code: 'PS',
    title: 'Palestinian Territory, Occupied',
    value: 'Palestinian Territory, Occupied',
  },
  { code: 'PA', title: 'Panama', value: 'Panama' },
  { code: 'PG', title: 'Papua New Guinea', value: 'Papua New Guinea' },
  { code: 'PY', title: 'Paraguay', value: 'Paraguay' },
  { code: 'PE', title: 'Peru', value: 'Peru' },
  { code: 'PH', title: 'Philippines', value: 'Philippines' },
  { code: 'PN', title: 'Pitcairn', value: 'Pitcairn' },
  { code: 'PL', title: 'Poland', value: 'Poland' },
  { code: 'PT', title: 'Portugal', value: 'Portugal' },
  { code: 'PR', title: 'Puerto Rico', value: 'Puerto Rico' },
  { code: 'QA', title: 'Qatar', value: 'Qatar' },
  { code: 'RE', title: 'Reunion', value: 'Reunion' },
  { code: 'RO', title: 'Romania', value: 'Romania' },
  { code: 'RU', title: 'Russian Federation', value: 'Russian Federation' },
  { code: 'RW', title: 'RWANDA', value: 'RWANDA' },
  { code: 'SH', title: 'Saint Helena', value: 'Saint Helena' },
  {
    code: 'KN',
    title: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
  },
  { code: 'LC', title: 'Saint Lucia', value: 'Saint Lucia' },
  {
    code: 'PM',
    title: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
  },
  {
    code: 'VC',
    title: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  { code: 'WS', title: 'Samoa', value: 'Samoa' },
  { code: 'SM', title: 'San Marino', value: 'San Marino' },
  {
    code: 'ST',
    title: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
  },
  { code: 'SA', title: 'Saudi Arabia', value: 'Saudi Arabia' },
  { code: 'SN', title: 'Senegal', value: 'Senegal' },
  {
    code: 'CS',
    title: 'Serbia and Montenegro',
    value: 'Serbia and Montenegro',
  },
  { code: 'SC', title: 'Seychelles', value: 'Seychelles' },
  { code: 'SL', title: 'Sierra Leone', value: 'Sierra Leone' },
  { code: 'SG', title: 'Singapore', value: 'Singapore' },
  { code: 'SK', title: 'Slovakia', value: 'Slovakia' },
  { code: 'SI', title: 'Slovenia', value: 'Slovenia' },
  { code: 'SB', title: 'Solomon Islands', value: 'Solomon Islands' },
  { code: 'SO', title: 'Somalia', value: 'Somalia' },
  { code: 'ZA', title: 'South Africa', value: 'South Africa' },
  {
    code: 'GS',
    title: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  },
  { code: 'ES', title: 'Spain', value: 'Spain' },
  { code: 'LK', title: 'Sri Lanka', value: 'Sri Lanka' },
  { code: 'SD', title: 'Sudan', value: 'Sudan' },
  { code: 'SR', title: 'Surivalue', value: 'Surivalue' },
  {
    code: 'SJ',
    title: 'Svalbard and Jan Mayen',
    value: 'Svalbard and Jan Mayen',
  },
  { code: 'SZ', title: 'Swaziland', value: 'Swaziland' },
  { code: 'SE', title: 'Sweden', value: 'Sweden' },
  { code: 'CH', title: 'Switzerland', value: 'Switzerland' },
  { code: 'SY', title: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
  {
    code: 'TW',
    title: 'Taiwan, Province of China',
    value: 'Taiwan, Province of China',
  },
  { code: 'TJ', title: 'Tajikistan', value: 'Tajikistan' },
  {
    code: 'TZ',
    title: 'Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
  },
  { code: 'TH', title: 'Thailand', value: 'Thailand' },
  { code: 'TL', title: 'Timor-Leste', value: 'Timor-Leste' },
  { code: 'TG', title: 'Togo', value: 'Togo' },
  { code: 'TK', title: 'Tokelau', value: 'Tokelau' },
  { code: 'TO', title: 'Tonga', value: 'Tonga' },
  { code: 'TT', title: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { code: 'TN', title: 'Tunisia', value: 'Tunisia' },
  { code: 'TR', title: 'Turkey', value: 'Turkey' },
  { code: 'TM', title: 'Turkmenistan', value: 'Turkmenistan' },
  {
    code: 'TC',
    title: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
  },
  { code: 'TV', title: 'Tuvalu', value: 'Tuvalu' },
  { code: 'UG', title: 'Uganda', value: 'Uganda' },
  { code: 'UA', title: 'Ukraine', value: 'Ukraine' },
  { code: 'AE', title: 'United Arab Emirates', value: 'United Arab Emirates' },
  { code: 'GB', title: 'United Kingdom', value: 'United Kingdom' },
  { code: 'US', title: 'United States', value: 'United States' },
  {
    code: 'UM',
    title: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  },
  { code: 'UY', title: 'Uruguay', value: 'Uruguay' },
  { code: 'UZ', title: 'Uzbekistan', value: 'Uzbekistan' },
  { code: 'VU', title: 'Vanuatu', value: 'Vanuatu' },
  { code: 'VE', title: 'Venezuela', value: 'Venezuela' },
  { code: 'VN', title: 'Viet Nam', value: 'Viet Nam' },
  {
    code: 'VG',
    title: 'Virgin Islands, British',
    value: 'Virgin Islands, British',
  },
  { code: 'VI', title: 'Virgin Islands, U.S.', value: 'Virgin Islands, U.S.' },
  { code: 'WF', title: 'Wallis and Futuna', value: 'Wallis and Futuna' },
  { code: 'EH', title: 'Western Sahara', value: 'Western Sahara' },
  { code: 'YE', title: 'Yemen', value: 'Yemen' },
  { code: 'ZM', title: 'Zambia', value: 'Zambia' },
  { code: 'ZW', title: 'Zimbabwe', value: 'Zimbabwe' },
]
