export { default as useShipping } from './use-shipping'
export { default as updateShipping } from './update-shipping'
export { default as updateAddress } from './update-address'
export { default as confirmOrder } from './confirm-order'
export { default as getOrderDetails } from './order-details'
export { default as getAltRelatedProducts} from './get-alt-related-product'
export { default as loqateUser } from './loqate'
export { retrieveAddress } from './loqate'
export { updateOrder } from './update-order'
export { default as getCustomerOrderDetails } from './customer-order-details'
