export const EVENTS_MAP: any = {
  EVENT_TYPES: {
    BasketItemAdded: 'BasketItemAdded',
    BasketItemRemoved: 'BasketItemRemoved',
    BasketViewed: 'BasketViewed',
    BrandViewed: 'BrandViewed',
    CategoryViewed: 'CategoryViewed',
    CheckoutConfirmation: 'CheckoutConfirmation',
    CheckoutStarted: 'CheckoutStarted',
    CmsPageViewed: 'CmsPageViewed',
    CollectionViewed: 'CollectionViewed',
    CustomerCreated: 'CustomerCreated',
    CustomerProfileViewed: 'CustomerProfileViewed',
    CustomerUpdated: 'CustomerUpdated',
    FacetSearch: 'FacetSearch',
    FaqViewed: 'FaqViewed',
    FreeText: 'FreeText',
    PageViewed: 'PageViewed',
    ProductViewed: 'ProductViewed',
    Search: 'Search',
  },
  ENTITY_TYPES: [
    'Basket',
    'Blog',
    'Brand',
    'Category',
    'CmsPage',
    'Collection',
    'Customer',
    'Order',
    'Page',
    'Product',
    'Search',
    'user',
  ],
  PAGE_CATEGORIES: [
    'Account',
    'B2B',
    'Basket',
    'Blog',
    'Brand',
    'Category',
    'Checkout',
    'Common',
    'Home',
    'Page',
    'Product',
    'Search',
    'Survey',
  ],
  CHANNEL_TYPES: ['Web', 'Mobile', 'App', 'Phone', 'Store'],
}
